## Sylvain SCHMITT
## 20/04/2021

# Ressources
ressources: "genologin.yaml"

# Source
genome:
   sequence: "Qrob_PM1N.fa" # Qrob_PM1N.fa.gz or Qrob_V2_2N.fa.gz
   genes: "Qrob_PM1N_genes_20161004.gff"
   TE: "Qrob_PM1N_refTEs.gff"

# Base reference
reference: "Qrob_Chr01:0-1000; Qrob_Chr02:0-1000"

# Mutations
mutations:
    # genic: 0 (homozygote)
    # te: 0 (homozygote)
    # heterozygote: 0 (non-genic, non-te)
    # homozygote: 0 (non-genic, non-te)
    number: 10
    R: 0.5 # transition/transversion ratio
    AF: 0.6 # allelic fraction

# Reads
sequencing:
    illumina: "hiseq"
    n_reads: 1000 # 150X : 1000bp ref/ 150bp reads * 150 cov
