## Sylvain SCHMITT
## 20/04/2021

# Ressources
ressources: "ressources.genologin.yaml"

# Sources
genome: "Qrob_PM1N"
L: 1000 # subsampled length
hz: "siteshz3P.vcf"
n_snps: 70 # pi = 0.01 , L = 7 kb , N = pi*L = 70 

# Mutations
n_mut: 100 # multivalues
R: 2 # transition/transversion ratio # multivalues

# Reads
AF: 0.6 # allelic fraction # multivalues
n_reads: 7000 # 150X : 50Mbp ref/ 150bp reads * 150 cov # multivalues
REP: [1, 2] # multivalues
