## Sylvain SCHMITT
## 20/04/2021

# Ressources
ressources: "genologin.yaml"

# Sources
sequence: "Qrob_PM1N"
genes: "Qrob_PM1N_genes_20161004.gff.gz"
TE: "Qrob_PM1N_refTEs.gff.gz"
hz: "siteshz3P.vcf"
chr: "Qrob_Chr01"
n_snps: 550 # pi = 0.01 , L = 55 Mb , N = pi*L = 550 

# Mutations
n_mut: 100 # multivalues
R: 2 # transition/transversion ratio # multivalues

# Reads
AF: 0.6 # allelic fraction # multivalues
n_reads: 50000 # 150X : 50Mbp ref/ 150bp reads * 150 cov # multivalues
