## Sylvain SCHMITT
## 20/04/2021

# Ressources
ressources: "ressources.genologin.yaml"

# Sources
genome: "Qrob_PM1N"
L: 1000000 # subsampled length
hz: "siteshz3P.vcf"
n_snps: 10000 # pi = 0.01 , L = 1 Mb , N = pi*L = 10^4

# Mutations
n_mut: 1000
R: 2 # transition/transversion ratio # multivalues

# Reads
AF: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.40, 0.5] # allelic fraction # multivalues
n_reads: [166667, 500000, 1000000] # [25, 50, 75, 100, 125, 150, 175, 200]X : 1Mb ref/ 150bp reads * cov # multivalues, paste(round(10^6/150*c(25, 50, 75, 100, 125, 150, 175, 200)), collapse = ", ")
REP: [1, 2, 3, 4, 5]
