## Sylvain SCHMITT
## 20/04/2021

# Ressources
ressources: "genologin.yaml"

# Reference
genome: "https://urgi.versailles.inra.fr/download/oak/Qrob_PM1N.fa.gz"
chromosome: "Qrob_Chr01"

# Generating reads
illumina: "hiseq"
n_reads: 100 # for test
# n_reads: 1000000
