__default__:
  jobname: "default"
  mem: "4G"
  cpus: 8
  time: "48:00:00"

cp_files:
  jobname: "cp_files"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
samtools_faidx:
  jobname: "samtools_faidx"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
vcf2model:
  jobname: "vcf2model"
  mem: "4G"
  cpus: 1
  time: "01:00:00"

simug:
  jobname: "simug"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
generate_mutations:
  jobname: "generate_mutations"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  
iss_base:
  jobname: "iss_base"
  mem: "16G"
  cpus: 4
  time: "01:00:00"
  
iss_mutated:
  jobname: "iss_mutated"
  mem: "16G"
  cpus: 4
  time: "01:00:00"
  
merge_reads:
  jobname: "merge_reads"
  mem: "4G"
  cpus: 1
  time: "01:00:00"
  